### ISSUE TITLE
Workaround for newer jsdom

### ISSUE THREAD

**Issue by zfLQ2qx2** [evelynhathaway/jest-location-mock#184]
Credit to ChatGPT for this, a workaround for newer jsdom where they make everything immutable, maybe this can get incorporated into your module

```
function mockLocation(windowObj) {
  const propertyDescriptors = Object.getOwnPropertyDescriptors(windowObj);
  for (const key in propertyDescriptors) {
    propertyDescriptors[key].configurable = true;
  }
  const clonedWindow = Object.defineProperties({}, propertyDescriptors);

  clonedWindow.Event = windowObj.Event;

  let hrefValue = '';

  Object.defineProperty(clonedWindow, 'location', {
    configurable: true,
    value: {
      get href() { return hrefValue; },
      set href(href) { hrefValue = href; }
    }
  });

  return clonedWindow;
}

...

global.window = mockLocation(window)

...
```

**Comment by evelynhathaway** [comment]
Can you provide the JSDOM version that is not working, the errors or behavior you experience, and a reproduction? This package already does something similar, so I am not sure what issue you may be experiencing that would lead you to generate this code.

**Comment by evelynhathaway** [comment]
I cannot reproduce this issue, and cannot without any further information.

If anyone runs across this thread, please report the issue you are experiencing with JSDOM, Jest, and jest-location-mock versions, and I will reopen. Do no use code you don't understand like the output from ChatGPT. The code provided is a lower quality workaround for mocking `window.location` and is incompatible with jest-location-mock.
