### ISSUE TITLE
TypeScript complains that property 'toBeAt' does not exist 

### ISSUE THREAD

**Issue by ArthurClemens** [evelynhathaway/jest-location-mock#2]
```
Property 'toBeAt' does not exist on type 'JestMatchersShape<Matchers<void, Location>, Matchers<Promise<void>, Location>>'. Did you mean 'toBe'?ts(2551)
```

![image](https://user-images.githubusercontent.com/350303/106773654-972abd00-6641-11eb-895f-8ab6ea6081fd.png)

**Comment by evelynhathaway** [comment]
Hi Arthur! I am sorry you are experiencing this error and thanks for reporting!

This error can appear whenever TypeScript doesn't load the types. I implemented some fixes and then used a [setup file similar to the one in the readme](https://github.com/evelynhathaway/jest-location-mock#setup) and it works for me now.

Can you confirm the changes in `v1.0.2` work for you?

**Comment by evelynhathaway** [comment]
Closed as fixed. Feel free to reopen if you experience any more issues.
